include ../Makefile.tests_common

# required modules
USEMODULE += dwax509m183x0

# required features
FEATURES_REQUIRED +=  periph_gpio
FEATURES_REQUIRED += periph_adc

include $(RIOTBASE)/Makefile.include
